find_path(GEOTIFF_INCLUDE_DIR NAMES geotiff.h
	PATHS ${CONAN_INCLUDE_DIRS_GEOTIFF}
	NO_DEFAULT_PATH)

find_library(GEOTIFF_LIBRARY NAMES ${CONAN_LIBS_GEOTIFF}
	PATHS ${CONAN_LIB_DIRS_GEOTIFF}
	NO_DEFAULT_PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GEOTIFF
	REQUIRED_VARS GEOTIFF_LIBRARY GEOTIFF_INCLUDE_DIR
	FOUND_VAR GEOTIFF_FOUND
)

set(GEOTIFF_INCLUDE_DIRS ${GEOTIFF_INCLUDE_DIR})
set(GEOTIFF_LIBRARIES ${GEOTIFF_LIBRARY})

mark_as_advanced(GEOTIFF_INCLUDE_DIR GEOTIFF_LIBRARY)
