find_path(GEOTIFF_INCLUDE_DIR NAMES geotiff.h
	PATHS ${CONAN_INCLUDE_DIRS_LIBGEOTIFF}
	NO_DEFAULT_PATH)

find_library(GEOTIFF_LIBRARY NAMES ${CONAN_LIBS_LIBGEOTIFF}
	PATHS ${CONAN_LIB_DIRS_LIBGEOTIFF}
	NO_DEFAULT_PATH)

find_package(TIFF REQUIRED)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GEOTIFF
	REQUIRED_VARS GEOTIFF_LIBRARY GEOTIFF_INCLUDE_DIR
	FOUND_VAR GEOTIFF_FOUND
)

set(GEOTIFF_INCLUDE_DIRS ${GEOTIFF_INCLUDE_DIR} ${TIFF_INCLUDE_DIRS})
set(GEOTIFF_LIBRARIES ${GEOTIFF_LIBRARY} ${TIFF_LIBRARIES})

mark_as_advanced(GEOTIFF_INCLUDE_DIR GEOTIFF_LIBRARY)
