find_package(TIFF REQUIRED)
find_package(PROJ4 REQUIRED)

find_path(GEOTIFF_INCLUDE_DIR NAMES geotiff.h
	PATHS ${CONAN_INCLUDE_DIRS_LIBGEOTIFF}
	NO_DEFAULT_PATH)

set(TMP_LIBRARIES "")
foreach(lib ${CONAN_LIBS_LIBGEOTIFF})
	unset(GEOTIFF_LIBRARY CACHE)
	find_library(GEOTIFF_LIBRARY NAMES ${lib}
		PATHS ${CONAN_LIB_DIRS_LIBGEOTIFF}
		NO_DEFAULT_PATH)
	list(APPEND TMP_LIBRARIES ${GEOTIFF_LIBRARY})
endforeach()
unset(GEOTIFF_LIBRARY CACHE)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GEOTIFF
	REQUIRED_VARS TMP_LIBRARIES GEOTIFF_INCLUDE_DIR)

set(GEOTIFF_INCLUDE_DIRS ${GEOTIFF_INCLUDE_DIR} ${TIFF_INCLUDE_DIRS} CACHE INTERNAL "")
set(GEOTIFF_LIBRARIES ${TMP_LIBRARIES} ${TIFF_LIBRARIES} ${PROJ4_LIBRARIES} CACHE INTERNAL "")

unset(GEOTIFF_INCLUDE_DIR CACHE)
